# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: install prerequisites
      run: |2-
        sudo apt update -y
        sudo apt install -y libopencv-dev
        sudo dpkg -l libopencv-dev

    - name: Vet
      run: go vet -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
