# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:

  build:


    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: phantom
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile
        extra-args: |
          --target=build
    - name: Run go vet
      run: podman run phantom:${{ github.sha }} go vet -v ./...
    - name: Run go test
      run: podman run phantom:${{ github.sha }} go test -v ./...

