# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

env:
  GOPATH: ${{ runner.temp }}/go

jobs:

  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: install prerequisites
      run: |2-
        go get -u -d gocv.io/x/gocv
        cd $GOPATH/src/gocv.io/x/gocv
        make install

    - name: Vet
      run: go vet -v ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
