# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:

  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - name: Buildah Action
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056
      with:
        image: ghcr.io/${{ github.repository }}
        tags: ${{ github.sha }}
        containerfiles: |
          ./Containerfile
        extra-args: |
          --target=build
    - name: Run go vet
      run: podman run ghcr.io/${{ github.repository }}:${{ github.sha }} go vet -v ./...
    - name: Run go test
      run: podman run ghcr.io/${{ github.repository }}:${{ github.sha }} go test -v ./...

